[package]
name = "shtui"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
color-eyre = "0.6.4"
inquire = "0.7.5"
ssh2-config = "0.5.4"
tokio = { version = "1.45.0", features = ["full"] }
