[package]
name = "sct"
version = "1.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
color-eyre = { version = "0.6.4", default-features = false }
inquire = "0.7.5"
ssh2-config = "0.5.4"
